/**
 * OpenApi specification - BZDATA
 *
 * Contact: michel.bossoh@outlook.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AuthenticationResponse { 
    token?: string;
}

