/**
 * OpenApi specification - BZDATA
 *
 * Contact: astairenazaire@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EleveRecordDTO { 
    nom?: string;
    prenoms?: string;
    dateNaissance?: string;
    sexe?: string;
    emailPersonnel?: string;
    codeDetcla?: string;
}

