/**
 * OpenApi specification - BZDATA
 *
 * Contact: astairenazaire@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EncaissementDTO { 
    sommeMontantEncais?: number;
    mois?: number;
    annee?: number;
    trimestre?: number;
    niveauLibelle?: string;
}

