/**
 * OpenApi specification - BZDATA
 *
 * Contact: astairenazaire@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PreinscriptionResponseDto { 
    id?: string;
    nomPrenoms: string;
    dateNaissance: string;
    lieuNaissance?: string;
    sexe: string;
    nationalite?: string;
    nationaliteIdentite: string;
    numeroIdentite: string;
    telephoneEtudiant?: string;
    cellulaireEtudiant: string;
    emailEtudiant?: string;
    villeEtudiant?: string;
    communeEtudiant?: string;
    baccalaureat?: string;
    anneeBac?: string;
    diplomeEquivalence?: string;
    anneeDiplomeEquivalence?: string;
    niveauEtudes?: string;
    anneeNiveauEtudes?: string;
    grade?: string;
    anneeGrade?: string;
    specialiteGrade?: string;
    etablissementFrequente?: string;
    formationSouhaitee: string;
    idPermanent?: string;
    nomPere?: string;
    nomMere?: string;
    titreResponsable?: string;
    responsable?: string;
    nomResponsable?: string;
    professionResponsable?: string;
    employeurResponsable?: string;
    villeResponsable?: string;
    communeResponsable?: string;
    boitePostaleResponsable?: string;
    cellulaireResponsable?: string;
    telephoneBureauResponsable?: string;
    telephoneDomicileResponsable?: string;
    emailResponsable?: string;
    copieBac?: string;
    copieDernierDiplome?: string;
    contactNomPrenom1?: string;
    contactAdresse1?: string;
    contactTelephone1?: string;
    contactCellulaire1?: string;
    contactNomPrenom2?: string;
    contactAdresse2?: string;
    contactTelephone2?: string;
    contactCellulaire2?: string;
    cliniqueDeclaree?: string;
    nomClinique?: string;
    telephoneClinique?: string;
    medecinClinique?: string;
    contactMedecin?: string;
    maladies?: string;
    soins?: string;
    medicaments?: string;
    premiersSoins?: string;
    interventionsChirurgicales?: string;
    decision?: string;
    numeroTable?: string;
    numeroMatricule?: string;
    totalBac?: number;
    matierePrincipale?: string;
    anneeScolaire?: string;
    etablissementSource?: string;
    inscritSousTitre?: boolean;
    utilisateurCreateur?: string;
    dateInscription?: string;
}

