/**
 * OpenApi specification - BZDATA
 *
 * Contact: astairenazaire@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PreinscriptionRequestDto { 
    id?: string;
    nomprenoms: string;
    datnais?: string;
    lieunais?: string;
    sexe?: string;
    nationalite?: string;
    natident?: string;
    numidentite?: string;
    teletud: string;
    celetud?: string;
    emailetud?: string;
    viletud?: string;
    cometud?: string;
    baccalaureat?: string;
    annbac?: string;
    diplequiv?: string;
    anndiplequiv?: string;
    nivoetud?: string;
    annivoetud?: string;
    grade?: string;
    anngrad?: string;
    specgrad?: string;
    etsfreq?: string;
    formsouh?: string;
    idperm?: string;
    nompere?: string;
    nomere?: string;
    titrespo?: string;
    respo?: string;
    nomrespo?: string;
    profrespo?: string;
    emprespo?: string;
    vilrespo?: string;
    comrespo?: string;
    bprespo?: string;
    celrespo?: string;
    telburespo?: string;
    teldomrespo?: string;
    emailrespo?: string;
    copiebac?: string;
    copderndipl?: string;
    contnompren1?: string;
    contadr1?: string;
    contel1?: string;
    contcel1?: string;
    contnompren2?: string;
    contadr2?: string;
    contel2?: string;
    contcel2?: string;
    clindec?: string;
    clinnom?: string;
    clintel?: string;
    clinmed?: string;
    clinmedcont?: string;
    maladies?: string;
    soins?: string;
    medic?: string;
    premsoins?: string;
    intervchir?: string;
    datinscrip?: string;
    decision?: string;
    numtabl?: string;
    numatri?: string;
    totbac?: number;
    matpc?: string;
    anneescolaire?: string;
    utilisateurCreateur?: string;
    etab_source?: string;
    inscrit_Sous_Titre?: boolean;
}

