/**
 * OpenApi specification - BZDATA
 *
 * Contact: astairenazaire@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Permission } from './permission';


export interface URole { 
    id?: number;
    idCreateur?: number;
    nomRole?: string;
    descriptionRole?: string;
    permission?: Set<Permission>;
}

