/**
 * OpenApi specification - BZDATA
 *
 * Contact: astairenazaire@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserRequest { 
    id?: number;
    username?: string;
    password?: string;
    nomPrenoms?: string;
    telephone?: string;
    email?: string;
    roleIds?: Set<number>;
}

