/**
 * OpenApi specification - BZDATA
 *
 * Contact: astairenazaire@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { URole } from './uRole';


export interface UserResponse { 
    id?: number;
    username?: string;
    enable?: boolean;
    statut?: UserResponse.StatutEnum;
    firstname?: string;
    lastname?: string;
    telephone?: string;
    email?: string;
    roles?: Array<URole>;
    createdDate?: string;
    lastModifiedDate?: string;
    formattedCreatedDate?: string;
}
export namespace UserResponse {
    export type StatutEnum = 'ACTIVE' | 'DESACTIVE' | 'SUSPENDUE';
    export const StatutEnum = {
        Active: 'ACTIVE' as StatutEnum,
        Desactive: 'DESACTIVE' as StatutEnum,
        Suspendue: 'SUSPENDUE' as StatutEnum
    };
}


