/**
 * OpenApi specification - BZDATA
 *
 * Contact: astairenazaire@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { URole } from './uRole';


export interface UserResponse { 
    id?: number;
    username?: string;
    enable?: boolean;
    firstname?: string;
    lastname?: string;
    telephone?: string;
    email?: string;
    roles?: Array<URole>;
    createdDate?: string;
    lastModifiedDate?: string;
    formattedCreatedDate?: string;
}

