export * from './authentication.service';
import { AuthenticationService } from './authentication.service';
export * from './eleves.service';
import { ElevesService } from './eleves.service';
export * from './encaissement.service';
import { EncaissementService } from './encaissement.service';
export * from './etablissement.service';
import { EtablissementService } from './etablissement.service';
export * from './fORMATION.service';
import { FORMATIONService } from './fORMATION.service';
export * from './permissions.service';
import { PermissionsService } from './permissions.service';
export * from './prinscription.service';
import { PrinscriptionService } from './prinscription.service';
export * from './roles.service';
import { RolesService } from './roles.service';
export * from './utilisateurController.service';
import { UtilisateurControllerService } from './utilisateurController.service';
export const APIS = [AuthenticationService, ElevesService, EncaissementService, EtablissementService, FORMATIONService, PermissionsService, PrinscriptionService, RolesService, UtilisateurControllerService];
