export * from './authentication.service';
import { AuthenticationService } from './authentication.service';
export * from './eleves.service';
import { ElevesService } from './eleves.service';
export * from './encaissement.service';
import { EncaissementService } from './encaissement.service';
export * from './etablissement.service';
import { EtablissementService } from './etablissement.service';
export * from './fORMATION.service';
import { FORMATIONService } from './fORMATION.service';
export * from './prinscription.service';
import { PrinscriptionService } from './prinscription.service';
export const APIS = [AuthenticationService, ElevesService, EncaissementService, EtablissementService, FORMATIONService, PrinscriptionService];
