/**
 * OpenApi specification - BZDATA
 *
 * Contact: astairenazaire@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec, HttpContext 
        }       from '@angular/common/http';
import { CustomHttpParameterCodec }                          from '../encoder';
import { Observable }                                        from 'rxjs';

// @ts-ignore
import { EleveRecordAvecPayerDto } from '../model/eleveRecordAvecPayerDto';
// @ts-ignore
import { EleveRecordDTO } from '../model/eleveRecordDTO';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import { BaseService } from '../api.base.service';



@Injectable({
  providedIn: 'root'
})
export class ElevesService extends BaseService {

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string|string[], @Optional() configuration?: Configuration) {
        super(basePath, configuration);
    }

    /**
     * @param paramClasse 
     * @param paramAnneDebut 
     * @param paramAnneFin 
     * @param paramEtab 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public etatListeEtudiant(paramClasse: string, paramAnneDebut: string, paramAnneFin: string, paramEtab: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/pdf', context?: HttpContext, transferCache?: boolean}): Observable<string>;
    public etatListeEtudiant(paramClasse: string, paramAnneDebut: string, paramAnneFin: string, paramEtab: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/pdf', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<string>>;
    public etatListeEtudiant(paramClasse: string, paramAnneDebut: string, paramAnneFin: string, paramEtab: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/pdf', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<string>>;
    public etatListeEtudiant(paramClasse: string, paramAnneDebut: string, paramAnneFin: string, paramEtab: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/pdf', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (paramClasse === null || paramClasse === undefined) {
            throw new Error('Required parameter paramClasse was null or undefined when calling etatListeEtudiant.');
        }
        if (paramAnneDebut === null || paramAnneDebut === undefined) {
            throw new Error('Required parameter paramAnneDebut was null or undefined when calling etatListeEtudiant.');
        }
        if (paramAnneFin === null || paramAnneFin === undefined) {
            throw new Error('Required parameter paramAnneFin was null or undefined when calling etatListeEtudiant.');
        }
        if (paramEtab === null || paramEtab === undefined) {
            throw new Error('Required parameter paramEtab was null or undefined when calling etatListeEtudiant.');
        }

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>paramClasse, 'paramClasse');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>paramAnneDebut, 'paramAnneDebut');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>paramAnneFin, 'paramAnneFin');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>paramEtab, 'paramEtab');

        let localVarHeaders = this.defaultHeaders;

        // authentication (bearerAuth) required
        localVarHeaders = this.configuration.addCredentialToHeaders('bearerAuth', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/pdf'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/eleves/etatListeEtudiant`;
        return this.httpClient.request<string>('get', `${this.configuration.basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                withCredentials: this.configuration.withCredentials,
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @param paramClasse 
     * @param paramAnneDebut 
     * @param paramAnneFin 
     * @param paramEtab 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public etatListeEtudiantExcel(paramClasse: string, paramAnneDebut: string, paramAnneFin: string, paramEtab: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<string>;
    public etatListeEtudiantExcel(paramClasse: string, paramAnneDebut: string, paramAnneFin: string, paramEtab: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<string>>;
    public etatListeEtudiantExcel(paramClasse: string, paramAnneDebut: string, paramAnneFin: string, paramEtab: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<string>>;
    public etatListeEtudiantExcel(paramClasse: string, paramAnneDebut: string, paramAnneFin: string, paramEtab: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (paramClasse === null || paramClasse === undefined) {
            throw new Error('Required parameter paramClasse was null or undefined when calling etatListeEtudiantExcel.');
        }
        if (paramAnneDebut === null || paramAnneDebut === undefined) {
            throw new Error('Required parameter paramAnneDebut was null or undefined when calling etatListeEtudiantExcel.');
        }
        if (paramAnneFin === null || paramAnneFin === undefined) {
            throw new Error('Required parameter paramAnneFin was null or undefined when calling etatListeEtudiantExcel.');
        }
        if (paramEtab === null || paramEtab === undefined) {
            throw new Error('Required parameter paramEtab was null or undefined when calling etatListeEtudiantExcel.');
        }

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>paramClasse, 'paramClasse');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>paramAnneDebut, 'paramAnneDebut');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>paramAnneFin, 'paramAnneFin');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>paramEtab, 'paramEtab');

        let localVarHeaders = this.defaultHeaders;

        // authentication (bearerAuth) required
        localVarHeaders = this.configuration.addCredentialToHeaders('bearerAuth', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            '*/*'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/eleves/etatListeEtudiantExcel`;
        return this.httpClient.request<string>('get', `${this.configuration.basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                withCredentials: this.configuration.withCredentials,
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @param anneeScolaire 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAllClasses(anneeScolaire: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<Array<string>>;
    public getAllClasses(anneeScolaire: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<Array<string>>>;
    public getAllClasses(anneeScolaire: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<Array<string>>>;
    public getAllClasses(anneeScolaire: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (anneeScolaire === null || anneeScolaire === undefined) {
            throw new Error('Required parameter anneeScolaire was null or undefined when calling getAllClasses.');
        }

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>anneeScolaire, 'anneeScolaire');

        let localVarHeaders = this.defaultHeaders;

        // authentication (bearerAuth) required
        localVarHeaders = this.configuration.addCredentialToHeaders('bearerAuth', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/eleves/getAllClasses`;
        return this.httpClient.request<Array<string>>('get', `${this.configuration.basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                withCredentials: this.configuration.withCredentials,
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @param promotions 
     * @param etablissements 
     * @param anneeScolaire 
     * @param startStr 
     * @param endStr 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getPromotionsEleves(promotions: Array<string>, etablissements: Array<string>, anneeScolaire: string, startStr: string, endStr: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<Array<EleveRecordDTO>>;
    public getPromotionsEleves(promotions: Array<string>, etablissements: Array<string>, anneeScolaire: string, startStr: string, endStr: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<Array<EleveRecordDTO>>>;
    public getPromotionsEleves(promotions: Array<string>, etablissements: Array<string>, anneeScolaire: string, startStr: string, endStr: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<Array<EleveRecordDTO>>>;
    public getPromotionsEleves(promotions: Array<string>, etablissements: Array<string>, anneeScolaire: string, startStr: string, endStr: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (promotions === null || promotions === undefined) {
            throw new Error('Required parameter promotions was null or undefined when calling getPromotionsEleves.');
        }
        if (etablissements === null || etablissements === undefined) {
            throw new Error('Required parameter etablissements was null or undefined when calling getPromotionsEleves.');
        }
        if (anneeScolaire === null || anneeScolaire === undefined) {
            throw new Error('Required parameter anneeScolaire was null or undefined when calling getPromotionsEleves.');
        }
        if (startStr === null || startStr === undefined) {
            throw new Error('Required parameter startStr was null or undefined when calling getPromotionsEleves.');
        }
        if (endStr === null || endStr === undefined) {
            throw new Error('Required parameter endStr was null or undefined when calling getPromotionsEleves.');
        }

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        if (promotions) {
            promotions.forEach((element) => {
                localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
                  <any>element, 'promotions');
            })
        }
        if (etablissements) {
            etablissements.forEach((element) => {
                localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
                  <any>element, 'etablissements');
            })
        }
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>anneeScolaire, 'anneeScolaire');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>startStr, 'startStr');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>endStr, 'endStr');

        let localVarHeaders = this.defaultHeaders;

        // authentication (bearerAuth) required
        localVarHeaders = this.configuration.addCredentialToHeaders('bearerAuth', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/eleves/getPromotionsEleves`;
        return this.httpClient.request<Array<EleveRecordDTO>>('get', `${this.configuration.basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                withCredentials: this.configuration.withCredentials,
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @param promotions 
     * @param etablissements 
     * @param anneeScolaire 
     * @param startStr 
     * @param endStr 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getPromotionsElevesExcel(promotions: Array<string>, etablissements: Array<string>, anneeScolaire: string, startStr: string, endStr: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<string>;
    public getPromotionsElevesExcel(promotions: Array<string>, etablissements: Array<string>, anneeScolaire: string, startStr: string, endStr: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<string>>;
    public getPromotionsElevesExcel(promotions: Array<string>, etablissements: Array<string>, anneeScolaire: string, startStr: string, endStr: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<string>>;
    public getPromotionsElevesExcel(promotions: Array<string>, etablissements: Array<string>, anneeScolaire: string, startStr: string, endStr: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (promotions === null || promotions === undefined) {
            throw new Error('Required parameter promotions was null or undefined when calling getPromotionsElevesExcel.');
        }
        if (etablissements === null || etablissements === undefined) {
            throw new Error('Required parameter etablissements was null or undefined when calling getPromotionsElevesExcel.');
        }
        if (anneeScolaire === null || anneeScolaire === undefined) {
            throw new Error('Required parameter anneeScolaire was null or undefined when calling getPromotionsElevesExcel.');
        }
        if (startStr === null || startStr === undefined) {
            throw new Error('Required parameter startStr was null or undefined when calling getPromotionsElevesExcel.');
        }
        if (endStr === null || endStr === undefined) {
            throw new Error('Required parameter endStr was null or undefined when calling getPromotionsElevesExcel.');
        }

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        if (promotions) {
            promotions.forEach((element) => {
                localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
                  <any>element, 'promotions');
            })
        }
        if (etablissements) {
            etablissements.forEach((element) => {
                localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
                  <any>element, 'etablissements');
            })
        }
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>anneeScolaire, 'anneeScolaire');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>startStr, 'startStr');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>endStr, 'endStr');

        let localVarHeaders = this.defaultHeaders;

        // authentication (bearerAuth) required
        localVarHeaders = this.configuration.addCredentialToHeaders('bearerAuth', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            '*/*'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/eleves/getPromotionsElevesExcel`;
        return this.httpClient.request<string>('get', `${this.configuration.basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                withCredentials: this.configuration.withCredentials,
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @param promotions 
     * @param etablissements 
     * @param anneeScolaire 
     * @param startStr 
     * @param endStr 
     * @param montantpayer 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getPromotionsElevesPayer(promotions: Array<string>, etablissements: Array<string>, anneeScolaire: string, startStr: string, endStr: string, montantpayer: number, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<Array<EleveRecordAvecPayerDto>>;
    public getPromotionsElevesPayer(promotions: Array<string>, etablissements: Array<string>, anneeScolaire: string, startStr: string, endStr: string, montantpayer: number, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<Array<EleveRecordAvecPayerDto>>>;
    public getPromotionsElevesPayer(promotions: Array<string>, etablissements: Array<string>, anneeScolaire: string, startStr: string, endStr: string, montantpayer: number, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<Array<EleveRecordAvecPayerDto>>>;
    public getPromotionsElevesPayer(promotions: Array<string>, etablissements: Array<string>, anneeScolaire: string, startStr: string, endStr: string, montantpayer: number, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (promotions === null || promotions === undefined) {
            throw new Error('Required parameter promotions was null or undefined when calling getPromotionsElevesPayer.');
        }
        if (etablissements === null || etablissements === undefined) {
            throw new Error('Required parameter etablissements was null or undefined when calling getPromotionsElevesPayer.');
        }
        if (anneeScolaire === null || anneeScolaire === undefined) {
            throw new Error('Required parameter anneeScolaire was null or undefined when calling getPromotionsElevesPayer.');
        }
        if (startStr === null || startStr === undefined) {
            throw new Error('Required parameter startStr was null or undefined when calling getPromotionsElevesPayer.');
        }
        if (endStr === null || endStr === undefined) {
            throw new Error('Required parameter endStr was null or undefined when calling getPromotionsElevesPayer.');
        }
        if (montantpayer === null || montantpayer === undefined) {
            throw new Error('Required parameter montantpayer was null or undefined when calling getPromotionsElevesPayer.');
        }

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        if (promotions) {
            promotions.forEach((element) => {
                localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
                  <any>element, 'promotions');
            })
        }
        if (etablissements) {
            etablissements.forEach((element) => {
                localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
                  <any>element, 'etablissements');
            })
        }
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>anneeScolaire, 'anneeScolaire');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>startStr, 'startStr');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>endStr, 'endStr');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>montantpayer, 'montantpayer');

        let localVarHeaders = this.defaultHeaders;

        // authentication (bearerAuth) required
        localVarHeaders = this.configuration.addCredentialToHeaders('bearerAuth', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/eleves/getPromotionsElevesPayer`;
        return this.httpClient.request<Array<EleveRecordAvecPayerDto>>('get', `${this.configuration.basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                withCredentials: this.configuration.withCredentials,
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

}
