/**
 * OpenApi specification - BZDATA
 *
 * Contact: astairenazaire@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec, HttpContext
        }       from '@angular/common/http';
import { CustomHttpParameterCodec }                          from '../encoder';
import { Observable }                                        from 'rxjs';

// @ts-ignore
import { EncaissementDTO } from '../model/encaissementDTO';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import { BaseService } from '../api.base.service';
import {DashboardEncaissementBIDTO} from '../model/DashboardEncaissementBIDTO';



@Injectable({
  providedIn: 'root'
})
export class EncaissementService extends BaseService {

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string|string[], @Optional() configuration?: Configuration) {
        super(basePath, configuration);
    }

    /**
     * @param etablissementSourceParam
     * @param paramDateDebut
     * @param paramDateFin
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public generateChiffreAffaireExcelDeFacturation(etablissementSourceParam: Array<string>, paramDateDebut: string, paramDateFin: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<string>;
    public generateChiffreAffaireExcelDeFacturation(etablissementSourceParam: Array<string>, paramDateDebut: string, paramDateFin: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<string>>;
    public generateChiffreAffaireExcelDeFacturation(etablissementSourceParam: Array<string>, paramDateDebut: string, paramDateFin: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<string>>;
    public generateChiffreAffaireExcelDeFacturation(etablissementSourceParam: Array<string>, paramDateDebut: string, paramDateFin: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (etablissementSourceParam === null || etablissementSourceParam === undefined) {
            throw new Error('Required parameter etablissementSourceParam was null or undefined when calling generateChiffreAffaireExcelDeFacturation.');
        }
        if (paramDateDebut === null || paramDateDebut === undefined) {
            throw new Error('Required parameter paramDateDebut was null or undefined when calling generateChiffreAffaireExcelDeFacturation.');
        }
        if (paramDateFin === null || paramDateFin === undefined) {
            throw new Error('Required parameter paramDateFin was null or undefined when calling generateChiffreAffaireExcelDeFacturation.');
        }

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        if (etablissementSourceParam) {
            etablissementSourceParam.forEach((element) => {
                localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
                  <any>element, 'etablissementSourceParam');
            })
        }
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>paramDateDebut, 'paramDateDebut');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>paramDateFin, 'paramDateFin');

        let localVarHeaders = this.defaultHeaders;

        // authentication (bearerAuth) required
        localVarHeaders = this.configuration.addCredentialToHeaders('bearerAuth', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            '*/*'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/encaissement/fichierExcelChiffreAffaire`;
        return this.httpClient.request<string>('get', `${this.configuration.basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                withCredentials: this.configuration.withCredentials,
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @param etablissementSourceParam
     * @param paramDateDebut
     * @param paramDateFin
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public generateEtatFacturationReport(etablissementSourceParam: Array<string>, paramDateDebut: string, paramDateFin: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<Array<EncaissementDTO>>;
    public generateEtatFacturationReport(etablissementSourceParam: Array<string>, paramDateDebut: string, paramDateFin: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<Array<EncaissementDTO>>>;
    public generateEtatFacturationReport(etablissementSourceParam: Array<string>, paramDateDebut: string, paramDateFin: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<Array<EncaissementDTO>>>;
    public generateEtatFacturationReport(etablissementSourceParam: Array<string>, paramDateDebut: string, paramDateFin: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (etablissementSourceParam === null || etablissementSourceParam === undefined) {
            throw new Error('Required parameter etablissementSourceParam was null or undefined when calling generateEtatFacturationReport.');
        }
        if (paramDateDebut === null || paramDateDebut === undefined) {
            throw new Error('Required parameter paramDateDebut was null or undefined when calling generateEtatFacturationReport.');
        }
        if (paramDateFin === null || paramDateFin === undefined) {
            throw new Error('Required parameter paramDateFin was null or undefined when calling generateEtatFacturationReport.');
        }

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        if (etablissementSourceParam) {
            etablissementSourceParam.forEach((element) => {
                localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
                  <any>element, 'etablissementSourceParam');
            })
        }
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>paramDateDebut, 'paramDateDebut');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>paramDateFin, 'paramDateFin');

        let localVarHeaders = this.defaultHeaders;

        // authentication (bearerAuth) required
        localVarHeaders = this.configuration.addCredentialToHeaders('bearerAuth', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/encaissement/etatFacturation`;
        return this.httpClient.request<Array<EncaissementDTO>>('get', `${this.configuration.basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                withCredentials: this.configuration.withCredentials,
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @param etablissementSourceParam
     * @param paramDateDebut
     * @param paramDateFin
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public generateFichierExcelDeFacturation(etablissementSourceParam: Array<string>, paramDateDebut: string, paramDateFin: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<string>;
    public generateFichierExcelDeFacturation(etablissementSourceParam: Array<string>, paramDateDebut: string, paramDateFin: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<string>>;
    public generateFichierExcelDeFacturation(etablissementSourceParam: Array<string>, paramDateDebut: string, paramDateFin: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<string>>;
    public generateFichierExcelDeFacturation(etablissementSourceParam: Array<string>, paramDateDebut: string, paramDateFin: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (etablissementSourceParam === null || etablissementSourceParam === undefined) {
            throw new Error('Required parameter etablissementSourceParam was null or undefined when calling generateFichierExcelDeFacturation.');
        }
        if (paramDateDebut === null || paramDateDebut === undefined) {
            throw new Error('Required parameter paramDateDebut was null or undefined when calling generateFichierExcelDeFacturation.');
        }
        if (paramDateFin === null || paramDateFin === undefined) {
            throw new Error('Required parameter paramDateFin was null or undefined when calling generateFichierExcelDeFacturation.');
        }

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        if (etablissementSourceParam) {
            etablissementSourceParam.forEach((element) => {
                localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
                  <any>element, 'etablissementSourceParam');
            })
        }
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>paramDateDebut, 'paramDateDebut');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>paramDateFin, 'paramDateFin');

        let localVarHeaders = this.defaultHeaders;

        // authentication (bearerAuth) required
        localVarHeaders = this.configuration.addCredentialToHeaders('bearerAuth', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            '*/*'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/encaissement/fichierExcleDeFacturation`;
        return this.httpClient.request<string>('get', `${this.configuration.basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                withCredentials: this.configuration.withCredentials,
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @param modeRegParam
     * @param etablissementSourceParam
     * @param paramDateDebut
     * @param paramDateFin
     * @param paramIDcaisse
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public generateJournalEncaissementsBetweenDatesReport(modeRegParam: Array<string>, etablissementSourceParam: Array<string>, paramDateDebut: string, paramDateFin: string, paramIDcaisse: number, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<string>;
    public generateJournalEncaissementsBetweenDatesReport(modeRegParam: Array<string>, etablissementSourceParam: Array<string>, paramDateDebut: string, paramDateFin: string, paramIDcaisse: number, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<string>>;
    public generateJournalEncaissementsBetweenDatesReport(modeRegParam: Array<string>, etablissementSourceParam: Array<string>, paramDateDebut: string, paramDateFin: string, paramIDcaisse: number, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<string>>;
    public generateJournalEncaissementsBetweenDatesReport(modeRegParam: Array<string>, etablissementSourceParam: Array<string>, paramDateDebut: string, paramDateFin: string, paramIDcaisse: number, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (modeRegParam === null || modeRegParam === undefined) {
            throw new Error('Required parameter modeRegParam was null or undefined when calling generateJournalEncaissementsBetweenDatesReport.');
        }
        if (etablissementSourceParam === null || etablissementSourceParam === undefined) {
            throw new Error('Required parameter etablissementSourceParam was null or undefined when calling generateJournalEncaissementsBetweenDatesReport.');
        }
        if (paramDateDebut === null || paramDateDebut === undefined) {
            throw new Error('Required parameter paramDateDebut was null or undefined when calling generateJournalEncaissementsBetweenDatesReport.');
        }
        if (paramDateFin === null || paramDateFin === undefined) {
            throw new Error('Required parameter paramDateFin was null or undefined when calling generateJournalEncaissementsBetweenDatesReport.');
        }
        if (paramIDcaisse === null || paramIDcaisse === undefined) {
            throw new Error('Required parameter paramIDcaisse was null or undefined when calling generateJournalEncaissementsBetweenDatesReport.');
        }

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        if (modeRegParam) {
            modeRegParam.forEach((element) => {
                localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
                  <any>element, 'modeRegParam');
            })
        }
        if (etablissementSourceParam) {
            etablissementSourceParam.forEach((element) => {
                localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
                  <any>element, 'etablissementSourceParam');
            })
        }
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>paramDateDebut, 'paramDateDebut');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>paramDateFin, 'paramDateFin');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>paramIDcaisse, 'paramIDcaisse');

        let localVarHeaders = this.defaultHeaders;

        // authentication (bearerAuth) required
        localVarHeaders = this.configuration.addCredentialToHeaders('bearerAuth', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            '*/*'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/encaissement/journalEncaissementsBetweenDates`;
        return this.httpClient.request<string>('get', `${this.configuration.basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                withCredentials: this.configuration.withCredentials,
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @param modeRegParam
     * @param etablissementSourceParam
     * @param paramDateDebut
     * @param paramDateFin
     * @param paramIDcaisse
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public generateJournalEncaissementsDroitInscriBetweenDatesReport(modeRegParam: Array<string>, etablissementSourceParam: Array<string>, paramDateDebut: string, paramDateFin: string, paramIDcaisse: number, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<string>;
    public generateJournalEncaissementsDroitInscriBetweenDatesReport(modeRegParam: Array<string>, etablissementSourceParam: Array<string>, paramDateDebut: string, paramDateFin: string, paramIDcaisse: number, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<string>>;
    public generateJournalEncaissementsDroitInscriBetweenDatesReport(modeRegParam: Array<string>, etablissementSourceParam: Array<string>, paramDateDebut: string, paramDateFin: string, paramIDcaisse: number, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<string>>;
    public generateJournalEncaissementsDroitInscriBetweenDatesReport(modeRegParam: Array<string>, etablissementSourceParam: Array<string>, paramDateDebut: string, paramDateFin: string, paramIDcaisse: number, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (modeRegParam === null || modeRegParam === undefined) {
            throw new Error('Required parameter modeRegParam was null or undefined when calling generateJournalEncaissementsDroitInscriBetweenDatesReport.');
        }
        if (etablissementSourceParam === null || etablissementSourceParam === undefined) {
            throw new Error('Required parameter etablissementSourceParam was null or undefined when calling generateJournalEncaissementsDroitInscriBetweenDatesReport.');
        }
        if (paramDateDebut === null || paramDateDebut === undefined) {
            throw new Error('Required parameter paramDateDebut was null or undefined when calling generateJournalEncaissementsDroitInscriBetweenDatesReport.');
        }
        if (paramDateFin === null || paramDateFin === undefined) {
            throw new Error('Required parameter paramDateFin was null or undefined when calling generateJournalEncaissementsDroitInscriBetweenDatesReport.');
        }
        if (paramIDcaisse === null || paramIDcaisse === undefined) {
            throw new Error('Required parameter paramIDcaisse was null or undefined when calling generateJournalEncaissementsDroitInscriBetweenDatesReport.');
        }

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        if (modeRegParam) {
            modeRegParam.forEach((element) => {
                localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
                  <any>element, 'modeRegParam');
            })
        }
        if (etablissementSourceParam) {
            etablissementSourceParam.forEach((element) => {
                localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
                  <any>element, 'etablissementSourceParam');
            })
        }
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>paramDateDebut, 'paramDateDebut');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>paramDateFin, 'paramDateFin');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>paramIDcaisse, 'paramIDcaisse');

        let localVarHeaders = this.defaultHeaders;

        // authentication (bearerAuth) required
        localVarHeaders = this.configuration.addCredentialToHeaders('bearerAuth', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            '*/*'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/encaissement/journalDroitInscBetweenDates`;
        return this.httpClient.request<string>('get', `${this.configuration.basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                withCredentials: this.configuration.withCredentials,
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @param etablissementSourceParam
     * @param paramDateDebut
     * @param paramDateFin
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public listeChiffreChiffreAffaire(etablissementSourceParam: Array<string>, paramDateDebut: string, paramDateFin: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<Array<EncaissementDTO>>;
    public listeChiffreChiffreAffaire(etablissementSourceParam: Array<string>, paramDateDebut: string, paramDateFin: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<Array<EncaissementDTO>>>;
    public listeChiffreChiffreAffaire(etablissementSourceParam: Array<string>, paramDateDebut: string, paramDateFin: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<Array<EncaissementDTO>>>;
    public listeChiffreChiffreAffaire(etablissementSourceParam: Array<string>, paramDateDebut: string, paramDateFin: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (etablissementSourceParam === null || etablissementSourceParam === undefined) {
            throw new Error('Required parameter etablissementSourceParam was null or undefined when calling listeChiffreChiffreAffaire.');
        }
        if (paramDateDebut === null || paramDateDebut === undefined) {
            throw new Error('Required parameter paramDateDebut was null or undefined when calling listeChiffreChiffreAffaire.');
        }
        if (paramDateFin === null || paramDateFin === undefined) {
            throw new Error('Required parameter paramDateFin was null or undefined when calling listeChiffreChiffreAffaire.');
        }

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        if (etablissementSourceParam) {
            etablissementSourceParam.forEach((element) => {
                localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
                  <any>element, 'etablissementSourceParam');
            })
        }
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>paramDateDebut, 'paramDateDebut');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>paramDateFin, 'paramDateFin');

        let localVarHeaders = this.defaultHeaders;

        // authentication (bearerAuth) required
        localVarHeaders = this.configuration.addCredentialToHeaders('bearerAuth', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/encaissement/listeChiffreChiffreAffaire`;
        return this.httpClient.request<Array<EncaissementDTO>>('get', `${this.configuration.basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                withCredentials: this.configuration.withCredentials,
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @param etablissementSourceParam
     * @param paramDateDebut
     * @param paramDateFin
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public listeFacturation(etablissementSourceParam: Array<string>, paramDateDebut: string, paramDateFin: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<Array<EncaissementDTO>>;
    public listeFacturation(etablissementSourceParam: Array<string>, paramDateDebut: string, paramDateFin: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<Array<EncaissementDTO>>>;
    public listeFacturation(etablissementSourceParam: Array<string>, paramDateDebut: string, paramDateFin: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<Array<EncaissementDTO>>>;
    public listeFacturation(etablissementSourceParam: Array<string>, paramDateDebut: string, paramDateFin: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (etablissementSourceParam === null || etablissementSourceParam === undefined) {
            throw new Error('Required parameter etablissementSourceParam was null or undefined when calling listeFacturation.');
        }
        if (paramDateDebut === null || paramDateDebut === undefined) {
            throw new Error('Required parameter paramDateDebut was null or undefined when calling listeFacturation.');
        }
        if (paramDateFin === null || paramDateFin === undefined) {
            throw new Error('Required parameter paramDateFin was null or undefined when calling listeFacturation.');
        }

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        if (etablissementSourceParam) {
            etablissementSourceParam.forEach((element) => {
                localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
                  <any>element, 'etablissementSourceParam');
            })
        }
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>paramDateDebut, 'paramDateDebut');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>paramDateFin, 'paramDateFin');

        let localVarHeaders = this.defaultHeaders;

        // authentication (bearerAuth) required
        localVarHeaders = this.configuration.addCredentialToHeaders('bearerAuth', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/encaissement/listeFacturation`;
        return this.httpClient.request<Array<EncaissementDTO>>('get', `${this.configuration.basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                withCredentials: this.configuration.withCredentials,
                headers: localVarHeaders,
                observe: observe,
                transferCache: localVarTransferCache,
                reportProgress: reportProgress
            }
        );
    }

  public getDashboardEncaissements(annee?: string, mois?: number, niveau?: string, observe?: 'body', reportProgress?: boolean, options?: { httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean }): Observable<DashboardEncaissementBIDTO>;
  public getDashboardEncaissements(annee?: string, mois?: number, niveau?: string, observe?: 'response', reportProgress?: boolean, options?: { httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean }): Observable<HttpResponse<DashboardEncaissementBIDTO>>;
  public getDashboardEncaissements(annee?: string, mois?: number, niveau?: string, observe?: 'events', reportProgress?: boolean, options?: { httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean }): Observable<HttpEvent<DashboardEncaissementBIDTO>>;
  public getDashboardEncaissements(annee?: string, mois?: number, niveau?: string, observe: any = 'body', reportProgress: boolean = false, options?: { httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean }): Observable<any> {

    let localVarQueryParameters = new HttpParams({ encoder: this.encoder });

    if (annee !== undefined && annee !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters, annee, 'annee'
      );
    }

    if (mois !== undefined && mois !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters, mois, 'mois'
      );
    }

    if (niveau !== undefined && niveau !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters, niveau, 'niveau'
      );
    }

    let localVarHeaders = this.defaultHeaders;

    // 🔐 Bearer Auth
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'bearerAuth',
      'Authorization',
      localVarHeaders,
      'Bearer '
    );

    const localVarHttpHeaderAcceptSelected =
      options?.httpHeaderAccept ??
      this.configuration.selectHeaderAccept(['application/json']);

    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set(
        'Accept',
        localVarHttpHeaderAcceptSelected
      );
    }

    const localVarHttpContext: HttpContext =
      options?.context ?? new HttpContext();

    const localVarTransferCache: boolean =
      options?.transferCache ?? true;

    let responseType_: 'json' | 'text' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (!this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'blob';
      }
    }

    const localVarPath = `/encaissement/dashboard`;

    return this.httpClient.request<DashboardEncaissementBIDTO>(
      'get',
      `${this.configuration.basePath}${localVarPath}`,
      {
        context: localVarHttpContext,
        params: localVarQueryParameters,
        responseType: <any>responseType_,
        withCredentials: this.configuration.withCredentials,
        headers: localVarHeaders,
        observe: observe,
        transferCache: localVarTransferCache,
        reportProgress: reportProgress
      }
    );
  }


}
